Add qtcharts for pyside6
conda-forge/pyside2-feedstock pull request #243
Opened 2024-10-08 08:30 UTC by amrutha0404

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

We are currently using QtCharts in our applications, but it is not supported in the existing setup. Therefore, we need to include the QtCharts DLLs to ensure that our applications continue to function properly with charting capabilities.

2024-10-08 08:32 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict. Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2024-10-08 09:51 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-10-08 11:00 UTC, hmaarrfk commented
It should work already. Just install qtcharts in your environment

2024-10-08 11:44 UTC, hmaarrfk requested changes
Unfortunately we decided to trim down qt6-core to give users smaller downloads and better control over the qt license they are using. 


In your case. It should all work if you add the package

qt6-charts

to your dependencies. We test for this in our build of python 3.10. 

Let me know if you have other questions. 


thank you for your involvement

2024-10-09 05:31 UTC, amrutha0404 commented
We were able to successfully download the qt6-charts package separately, so I will close this PR as it is no longer required. Thanks for the support!

2024-10-09 05:31 UTC, closed without merging